# Generated by Django 5.2.4 on 2025-08-05 05:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users_image/default_user.jpg', null=True, upload_to=users.models.UploadToUniquePath('users_image')),
        ),
    ]
