# Generated by Django 5.2.4 on 2025-07-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cover_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
