# Generated by Django 5.2.4 on 2025-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_cover_url_alter_events_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cover_url',
            field=models.ImageField(blank=True, default='event_image/default_image.jpg', null=True, upload_to='event_image'),
        ),
    ]
